replicaCount: 2

image:
  repository: my-app
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  name: my-app-ingress
  nginx.ingress.kubernetes.io/rewrite-target: /
